### ISSUE TITLE
⚠️[Attention] Changes to "geosite:ads"

### ISSUE THREAD

**Issue by Chocolate4U** [Chocolate4U/Iran-sing-box-rules#1]
With the help of some 99% chocolate bars, I realized that after [this commit](https://github.com/Chocolate4U/Iran-v2ray-rules/commit/335a956ca70c363353b6e1853a74223bc6da6c83) which was mainly for compatibility reasons, and also because people used to `category-ads-all` for blocking all ads, the new `geosite:category-ads-all` which was simply a duplicate of `geosite:ads` is causing the file to become too large. to address this problem I have made the following changes:

:point_right: `geosite:ads` will only block Persian Ads now.  
:point_right: `geosite:category-ads-all` will block All Ads now. Including Persian Ads.

Also I have added new `lite` edition of files for devices with extremely limited storage space.  

Sorry for any inconveniences and please update your configurations accordingly.

**Comment by fakhamatia** [comment]
درود
آیا داخل `category-ads-all` این ریپو، موارد داخل ریپو اصلی domain-list-community برای `category-ads-all` موجوده؟ 

و اینکه اگر از `category-ads-all` استفاده کنم نیاز هست `geosite:ads` هم وارد کنم؟

@Chocolate4U

**Comment by Chocolate4U** [comment]
درود
نه، سورس دامنه های تبلیغاتی این ریپو متفاوت از [domain-list-community](https://github.com/v2fly/domain-list-community) هست، و از سورس های معتبرتری که به روزرسانی مرتب تری دارن استفاده شده که هم تبلیغات بیشتری رو مسدود میکنه و هم false positive کمتری داره. البته خیلی از دامنه های تبلیغاتی این ریپو با [domain-list-community](https://github.com/v2fly/domain-list-community) همپوشانی داره اما این که دقیقا از اون دیتابیس استفاده شده باشه نه اینطور نیست.
در صورت استفاده از `category-ads-all`، نیازی به `geosite:ads` نیست و داخل همون `category-ads-all` لحاظ شده.

**Comment by fakhamatia** [comment]
> درود نه، سورس دامنه های تبلیغاتی این ریپو متفاوت از [domain-list-community](https://github.com/v2fly/domain-list-community) هست، و از سورس های معتبرتری که به روزرسانی مرتب تری دارن استفاده شده که هم تبلیغات بیشتری رو مسدود میکنه و هم false positive کمتری داره. البته خیلی از دامنه های تبلیغاتی این ریپو با [domain-list-community](https://github.com/v2fly/domain-list-community) همپوشانی داره اما این که دقیقا از اون دیتابیس استفاده شده باشه نه اینطور نیست.


درسته. به همین موضوع شک داشتم چون چند روز پیش چندتا دامنه به `domain-list-community` اضافه کردم. وقتی PR رو قبول کردن و ریلیز دادن و شما هم ریلیز دادید تست کردم دیدم تبلیغات مورد نظر بلاک نمیشه. این منابع کجا هستند؟ راهی برای مشارکت و اضافه کردن دامنه های تبلیغات و ترکر غیر ایرانی هست؟
و یک سوال دیگه اینکه برای مشارکت و اضافه کردن دامنه های ایرانی غیر ir. منبع [iran-hosted-domains](https://github.com/bootmortis/iran-hosted-domains) هست؟

**Comment by Chocolate4U** [comment]
انتهای ریپو لیست تمامی منابع آورده شده [Sources](https://github.com/Chocolate4U/Iran-sing-box-rules#package-sources)
منبع اصلی [dns-blocklists](https://github.com/hagezi/dns-blocklists) هست و بقیه به عنوان تکمیلی استفاده میشن
میتونید دامنه های مورد نظرتون رو به اونجا PR بزنین، maintainer خیلی فعالی داره و سریعا بررسی میکنه معمولا
دقت کنین که من از سبک‌ترین لیست یعنی "Multi LIGHT" استفاده کردم و ممکنه دامنه های شما توی لیست های بزرگتر hagezi باشه. این مورد رو چک کنید.
استفاده از لیست های بزرگتر از LIGHT برای روتینگ مناسب نیست، چون هم حجم فایل بالا میره و هم بار پردازشی سنگینی به خصوص روی دستگاه های موبایل نه چندان قدرتمند ایجاد میکنه که در عملکرد پروکسی تاثیر منفی میزاره.

**Comment by fakhamatia** [comment]
ببخشید من سوال زیاد میپرسم. اگر Discussions باز بود اونجا مطرح میکردم، یا مثلا گروه تلگرامی.
دامنه ای که میخواستم بلاک بشه از قبل داخل `dns-blocklists` هست ولی توی لیست های بزرگتر از LIGHT، چون از AdGuard DNS استفاده میکنم و توی رایگان محدویت تعداد درخواست داره میخواستم داخل خود کلاینت بسته بشن.

من لیست `category-public-tracker` رو هم بلاک میکنم در صورت استفاده از ‍‍`category-ads-all` حذف بشه یا بذارم بمونه؟
و همینطور لیست `category-ir` رو دایرکت میکنم. با وجود `geosite:ir` حذف بشه یا بذارم بمونه؟

**Comment by Chocolate4U** [comment]
ترکر هایی که باعث ایجاد مشکل در لود شدن سایت ها نمیشن توی `category-ads-all` هست و بلاک میشن. دقیقا بررسی نکردم چه ترکرهایی داخل `category-public-tracker` هست و ممکنه همه از قبل داخل `category-ads-all` وجود داشته باشن، در کل فقط لیست `category-ads-all` با [domain-list-community](https://github.com/v2fly/domain-list-community) متفاوته و سایر لیست های اون ریپو رو میشه در کنار لیست های این ریپو استفاده کرد.

لیست `category-ir` به طور کامل در `geosite:ir` وجود داره و نیازی به استفاده ازش نیست.
