### ISSUE TITLE
درخواست بر مبنای فرمت جدید

### ISSUE THREAD

**Issue by Graveyard9988** [Chocolate4U/Iran-sing-box-rules#11]
درود
در صورت امکان با فرمت جدید srs، موارد زیر را ایجاد و اضافه کنید:
geoip-af
geoip تمام کشور ها
geosite تمام کشور ها
geoip-private

سپاس

**Comment by Chocolate4U** [comment]
سلام
کلیه این موارد اضافه شده، از [اینجا](https://github.com/Chocolate4U/Iran-sing-box-rules/tree/rule-set) میتونید لیست کامل فایل ها با فرمت جدید را ببینید.

**Comment by Graveyard9988** [comment]
لیست نامبرده طولانی ست و خیلی از موارد را نشان نمی دهد . ایا راهکاری برای مشاهده همه ی ان ها دارید؟

> سلام کلیه این موارد اضافه شده، از [اینجا](https://github.com/Chocolate4U/Iran-sing-box-rules/tree/rule-set) میتونید لیست کامل فایل ها با فرمت جدید را ببینید.

**Comment by Chocolate4U** [comment]
> لیست نامبرده طولانی ست و خیلی از موارد را نشان نمی دهد . ایا راهکاری برای مشاهده همه ی ان ها دارید؟
> 
> > سلام کلیه این موارد اضافه شده، از [اینجا](https://github.com/Chocolate4U/Iran-sing-box-rules/tree/rule-set) میتونید لیست کامل فایل ها با فرمت جدید را ببینید.

این محدودیت گیت هاب هست، برای اینکه لیست کامل فایل ها را ببینید باید این مخزن را روی سیستم خودتان clone کنید. اگر با این کار آشنایی ندارید، "نحوه clone کردن مخزن گیت هاب" را در اینترنت جستجو کنید، آموزش های زیادی برای این کار وجود داره.

**Comment by Graveyard9988** [comment]
بسیار سپاسگزارم
