### ISSUE TITLE
درخواست مهم

### ISSUE THREAD

**Issue by Graveyard9988** [Chocolate4U/Iran-sing-box-rules#14]
درود
خواهشمندم لیست اپ های ایرانی در rule-provider کلش به کار گرفته می شوند را در فرمت srs برای سینگ باکس مهیا سازی. در ذیل، نمونه ای به صورت جیسون برای شما اورده شده : 
https://github.com/senzyo/sing-box-rules/blob/sing/bm7/Download.json

ودر ادامه با فرمت srs به شرح ذیل است:
        "tag": "bm7-Download",
        "type": "remote",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/senzyo/sing-box-rules/sing/bm7/Download.srs",
        "download_detour": "direct",
        "update_interval": "3d"
        
        نکته: بخش update_interval به تازگی اضافه شده پس حتی الامکان در مستندات خود بیفزایید تا کاربران به اپدیت خودکار دسترسی داشته باشند.

سپاس

**Comment by Chocolate4U** [comment]
تا جایی یادم هست سینگ باکس قابلیت خواندن لیست اپلیکیشن ها را از فایل های جئو نداشت، اما دوباره بررسی میکنم اکثر امکانپذیر بود، اضافه میشه.
