### ISSUE TITLE
Great resource 

### ISSUE THREAD

**Issue by Graveyard9988** [Chocolate4U/Iran-sing-box-rules#2]
Great resource for blocking persian ads:
https://github.com/MasterKia/iran-hosted-domains/

Great resource for bypassing persian sites:
https://github.com/bootmortis/iran-hosted-domains/

Great resource for persian geoip.db:
https://github.com/MiSaturo/sing-box-geoip-ir

**Comment by Chocolate4U** [comment]
سلام
دو مورد اول که همین الان از سورس های ریپو هستن
مورد سوم هم به طور کامل تر از دیتابیس MaxMind به علاوه IP پیام رسان های ایرانی در ریپو هست.

**Comment by Graveyard9988** [comment]
بسیار عالی
سپاس بی کران
