### ISSUE TITLE
اضافه کردن رنج ای پی های ایران اپدیت 2024

### ISSUE THREAD

**Issue by moli1369** [Chocolate4U/Iran-sing-box-rules#20]
[ip Iran 2024.txt](https://github.com/Chocolate4U/Iran-sing-box-rules/files/14623033/ip.Iran.2024.txt)
این فایل رنج تمامی ای پی های ایران تا به امروز هست خواستی اپدیت کنی به سایت ip2loctaion مراجعه کن

یه این ادرس تمامی ای پی های ورژن 6 و 4  ایران را به روز میده بهتون 
ممنون میشم اپدیت کنی چون بعضی از اپ ها هنوز با اینکه این دیتا رو بهش دادیم ولی میشناسن و باز نمیکنن.
فدات

**Comment by Chocolate4U** [comment]
سلام
دیتابیس IP2Location خیلی وقته به مخزن اضافه شده و طبق به روزرسانی خود IP2Location که یکم و پانزدهم هر ماه میلادیه به روزسانی میشه.
[IP2Location](https://github.com/Chocolate4U/Iran-v2ray-rules/tree/ip2location)
