### ISSUE TITLE
Critical request

### ISSUE THREAD

**Issue by Graveyard9988** [Chocolate4U/Iran-sing-box-rules#21]
سه کلاینت زیر منوی انتخاب شکلات در تنظیمات را دارند اما به خاطر هسته‌ی جدید سینگ، فایل های srs شکلات را ندارند و بنابراین کرش می کنند یا با اررور مواجه می شویم. لطفا تغییرات لازمه را به دو ریپو زیر pull request بزنید چرا که من برنامه نویس نیستم و از طرفی کلاینت های جدید با مشکلات و باگ‌های کمتری مواجهند. دو ریپو به شرح ذیل است:

https://github.com/xchacha20-poly1305/husi

https://github.com/maskedeken/NekoBoxForAndroid

https://github.com/MatsuriDayo/NekoBoxForAndroid

لازم به ذکر است کلاینت دوم به دلیل داشتن فرگمنت مورد استفاده بسیاری قرار می گیرد بنابراین پول ریکوئست کلاینت های دوم و سوم یکسان خواهد بود و زحمت آن را متقبل شوید

سپاس بی کران

**Comment by Chocolate4U** [comment]
سلام
با کلاینت husi زیاد آشنایی ندارم و باید بررسی کنم، اما برای NekoBox سعی میکنم در اولین فرصت اضافه کنم.
