### ISSUE TITLE
عدم بای پس شدن دیجی‌کالا

### ISSUE THREAD

**Issue by Graveyard9988** [Chocolate4U/Iran-sing-box-rules#22]
با فایل های srs شکلات، امروز در باز استفاده کردن از سایت نامبرده با مشکل مواجه شدم چرا که پس از باز شدن سایت، محتوای داخل آن ناقص لود شده و خطای "خطا در دریافت اطلاعات، باشه" را مکررا دیدم تا اینکه سینگ باکس را قطع کردم

**Comment by Chocolate4U** [comment]
سلام،


> با فایل های srs شکلات، امروز در باز استفاده کردن از سایت نامبرده با مشکل مواجه شدم چرا که پس از باز شدن سایت، محتوای داخل آن ناقص لود شده و خطای "خطا در دریافت اطلاعات، باشه" را مکررا دیدم تا اینکه سینگ باکس را قطع کردم

من امروز بررسی کردم، مشکلی نداشتم، 
1. میتونید دوباره تست کنید ببینید مشکل حل شده یا نه؟
2. اگه حل نشده، سایت دیگه ای به غیر از دیجیکالا هست که این مشکل رو داشته باشه؟
3. در صورت امکان، لاگ sing-box درحالت "debug" رو هم قرار بده.


> درود بر شما. طبق گزارش یکی از کاربران، مشکل از سمت لیست PersianBlocker هست اما نمی‌دونم از کدوم فیلترشه تا حذفش کنم. شما می‌تونید متوجه بشید؟

اگر مشکل از PersianBlocker باشه باید کاربران uBlock هم به مشکل خورده باشن، همینطوره یا فقط کاربرایی که از پروکسی استفاده کردن به مشکل خوردن؟
