### ISSUE TITLE
کمک و راهنمایی

### ISSUE THREAD

**Issue by Graveyard9988** [Chocolate4U/Iran-sing-box-rules#23]
در روتر هایی که passwall2 نصب شده است، در بخش rule manage، ادرس های DB های Loyalsoldier درج شده است. بدین صورت:
https://api.github.com/repos/Loyalsoldier/v2ray-rules-dat/releases/latest
و
https://api.github.com/repos/Loyalsoldier/v2ray-rules-dat/releases/latest

اگر ممکن است، در قالب فوق نیز لینک های اشتراک DB بسازید تا جایگزین پیشفرض کنیم

سپاس

**Comment by Chocolate4U** [comment]
سلام،
تجربه کار با passwall2 را ندارم، اما این api استاندارد گیت هاب هست و با سایر مخازن هم باید کار کنه. به این صورت تست کنید ببینید جواب می گیرید:
[https://api.github.com/repos/Chocolate4U/Iran-sing-box-rules/releases/latest](https://api.github.com/repos/Chocolate4U/Iran-sing-box-rules/releases/latest)
