### ISSUE TITLE
Help opening and checking db files 

### ISSUE THREAD

**Issue by papampi** [Chocolate4U/Iran-sing-box-rules#24]
Anyway we can open db files or check rule-sets srs files to see which domains or geosites are in sets?

**Comment by Chocolate4U** [comment]
Hi, Sorry for late reply.
Technically, you can. But you have to write the code for it. For `.dat` files you can use this repository [geo](https://github.com/MetaCubeX/geo), but for `.db` and `.srs` files I didn't see any ready-made tool.
Basically you have to reverse the code logic of sing-box geo asset generation in these repositories [geoip](https://github.com/SagerNet/sing-geoip) [geosite](https://github.com/SagerNet/sing-geosite)

**Comment by papampi** [comment]
Thanks will check it out
