### ISSUE TITLE
Bypass issue

### ISSUE THREAD

**Issue by Graveyard9988** [Chocolate4U/Iran-sing-box-rules#25]
Check my Iran**Cell App to ensure that ip or domains are bypassed because by using openwrt (passwall2) with your DB files, my iran**cell app persists that I'm using vpn!

Regards

**Comment by Chocolate4U** [comment]
سلام،
اپلیکیشن ایرانسل من دامنه [www.cloudflare.com](http://www.cloudflare.com) رو چک میکنه که مستقیم وصل میشه یا با پروکسی. این دامنه رو اگر بزارید تو لیست بایپس بدون مشکل باز میشه.
