### ISSUE TITLE
[Feature Request] Adding oisd blocklist

### ISSUE THREAD

**Issue by molink36** [Chocolate4U/Iran-sing-box-rules#29]
I believe oisd to be the best blocklist with the least false-positive among blocklists (for ads and nsfw).
Please consider adding "oisd small", "oisd big" and "oisd nsfw" to the list of domains.

Links:

[oisd](https://oisd.nl/)
[oisd setup](https://oisd.nl/setup)

**Comment by Chocolate4U** [comment]
Yes, OISD lists are very comprehensive and a good resource in general but they're too big for VPN clients and routing purposes. Also the geo files will become too large which is not ideal for daily updates.
