### ISSUE TITLE
Routing for V2rayN

### ISSUE THREAD

**Issue by JWick90** [Chocolate4U/Iran-sing-box-rules#30]
سلام خسته نباشید
من هرچقدر آموزش استفاده رو خوندم انجام دادم ولی کار نکرد
دقیقا نحوه استفاده و فعال کردن روتینگ روی v2rayN چطور هست؟
برای xray اوکیه ولی سینگ باکس چطوریه؟
برای استفاده با هیستریا2.

**Comment by Chocolate4U** [comment]
سلام
متاسفانه v2rayn روی هسته sing-box اجبارا فقط از فایل های روتینگ loyalsoldier استفاده میکنه و قابلیت تغییر هم نداره.
باید کاستوم کانفیگ بسازید و اونجا آدرس فایل ها و تنظیمات روتینگ رو بدید بهش.

**Comment by Chocolate4U** [comment]
> > سلام متاسفانه v2rayn روی هسته sing-box اجبارا فقط از فایل های روتینگ loyalsoldier استفاده میکنه و قابلیت تغییر هم نداره. باید کاستوم کانفیگ بسازید و اونجا آدرس فایل ها و تنظیمات روتینگ رو بدید بهش.
> 
> پس بخاطر اینه هرکار کردم درست نشد که نشد فکر میکنم سیستم روتینگ v2rayNG هم مثل دسکتاپش شده باشه عوض شده تازگی درسته ؟ و اینکه جایی کانورتر هست برای تبدیل هیستریا ؟ یا مثلا آموزشی چیزی برای کاستوم کردن ؟ ممنونتم

عذر میخوام ریپلی شما رو ندیده بودم.
بله v2rayng هم تغییرات داشته اما فقط تو بخش ui بوده و همچنان از همون فرمت قبلی استفاده میکنه. فقط نحوه کانفیگش عوض شده.
اگه منظور هسته خود Hysteria2 هست که فکر کنم از فرمت فایل های `dat.` v2ray پشتیبانی میکنه و نیازی به کانورتر نیست. برای سینگ باکس هم مخزن های زیادی کانفیگ کاستوم نمونه براش گذاشتن. سرچ کنید پیدا میکنید.
