### ISSUE TITLE
Whatsapp geo ip 

### ISSUE THREAD

**Issue by roozbehalamdari** [Chocolate4U/Iran-sing-box-rules#32]
درود بر شما و سپاس از زحماتتون 
ببخشید برای سینگ باکس ورژن 1.10.1 به بالا ،  geo ip واتس اپ رو میخواستم ولی پیدا نکردم لطفا اونو بهم میدید ؟ سپاس گذارم ♥
برای تلگرام رو پیدا کردم ولی واتس اپ رو نه 

https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geoip-telegram.srs

**Comment by BehradJi** [comment]
سلام، میتونین از geosite استفاده کنید:
https://github.com/Chocolate4U/Iran-sing-box-rules/raw/refs/heads/rule-set/geosite-whatsapp.srs

**Comment by roozbehalamdari** [comment]
> سلام، میتونین از geosite استفاده کنید: https://github.com/Chocolate4U/Iran-sing-box-rules/raw/refs/heads/rule-set/geosite-whatsapp.srs

سپاس از راهنماییت بهراد جان ، فقط یه سوال داشتم 
من برای پنل S-UI میخواهم واتس اپ geo ip رو توی Ruleset اضافه کنم که ترافیکش از وارپ رد نشه و دایرکت رد بشه ، آیا geosite هم جواب میده ؟ چون اضافه کردم ولی کلا دیگه پیامی نمیشه فرستاد توی واتس اپ 
ممنونم میشم اگر بیشتر راهنماییم کنی 🙏

**Comment by BehradJi** [comment]
تا جایی که من اطلاع دارم Geoip شامل آی پی های اون سرویس میشه و Geosite شامل دامنه های اون سرویس هست برای همین تفاوتی نداره و باید کار کنه ولی در مورد پنلی که گفتید اطلاعی ندارم.
محتوای`geosite-whatsapp.srs` :
```json
{
  "version": 1,
  "rules": [
    {
      "domain_suffix": [
        "graph.whatsapp.com",
        "graph.whatsapp.net",
        "wa.me",
        "whatsapp-plus.info",
        "whatsapp-plus.me",
        "whatsapp-plus.net",
        "whatsapp.cc",
        "whatsapp.com",
        "whatsapp.info",
        "whatsapp.net",
        "whatsapp.org",
        "whatsapp.tv",
        "whatsappbrand.com"
      ]
    }
  ]
}

```
محتوای `geoip-telegram.srs` : 
``` json
{
  "version": 1,
  "rules": [
    {
      "ip_cidr": [
        "91.105.192.0/23",
        "91.108.4.0/22",
        "91.108.8.0/21",
        "91.108.16.0/21",
        "91.108.56.0/22",
        "149.154.160.0/20",
        "185.76.151.0/24",
        "2001:67c:4e8::/48",
        "2001:b28:f23c::/47",
        "2001:b28:f23f::/48",
        "2a0a:f280::/32"
      ]
    }
  ]
}

```

**Comment by Chocolate4U** [comment]
> درود بر شما و سپاس از زحماتتون ببخشید برای سینگ باکس ورژن 1.10.1 به بالا ، geo ip واتس اپ رو میخواستم ولی پیدا نکردم لطفا اونو بهم میدید ؟ سپاس گذارم ♥ برای تلگرام رو پیدا کردم ولی واتس اپ رو نه
> 
> https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geoip-telegram.srs


سلام،
واتساپ و کلا اکوسیستم متا، از یک سیستم توزیع محتوای یکپارچه استفاده میکنن و جداسازی IP های هریک از اون ها امکان پذیر نیست.
میتونید از این فایل استفاده کنید که شامل IP های فیسبوک، اینستاگرام، واتساپ و سایر سرویس های متا هست:
https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geoip-facebook.srs

**Comment by roozbehalamdari** [comment]
> > درود بر شما و سپاس از زحماتتون ببخشید برای سینگ باکس ورژن 1.10.1 به بالا ، geo ip واتس اپ رو میخواستم ولی پیدا نکردم لطفا اونو بهم میدید ؟ سپاس گذارم ♥ برای تلگرام رو پیدا کردم ولی واتس اپ رو نه
> > 
> > https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geoip-telegram.srs
> 
> 
> سلام،
> واتساپ و کلا اکوسیستم متا، از یک سیستم توزیع محتوای یکپارچه استفاده میکنن و جداسازی IP های هریک از اون ها امکان پذیر نیست.
> میتونید از این فایل استفاده کنید که شامل IP های فیسبوک، اینستاگرام، واتساپ و سایر سرویس های متا هست:
> https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geoip-facebook.srs

سپاسگذارم از توضیحات کاملتون 🙏 
یه سوال دیگه هم داشتم برای تبلیغات یوتیوب سورس کاملی نیومده ؟ یا پیشنهادتون چیه ؟ چون توی رولز تعریف میکنم ولی همچنان تبلیغات یوتیوب رو نشون میده 🤔

**Comment by Chocolate4U** [comment]
تبلیغات یوتیوب چون از دامنه یکسان با ویدیوها استفاده میکنن، مسدود کردنشون از طریق DNS امکان پذیر نیست و فقط میشه از سمت کلاینت به کمک Content Filtering ها مثل افزونه Ublock Origin مسدودشون کرد.

**Comment by roozbehalamdari** [comment]
> تبلیغات یوتیوب چون از دامنه یکسان با ویدیوها استفاده میکنن، مسدود کردنشون از طریق DNS امکان پذیر نیست و فقط میشه از سمت کلاینت به کمک Content Filtering ها مثل افزونه Ublock Origin مسدودشون کرد.

یک دنیا سپاس از شما و راهنماییتون ، واتس اپ هم با سورسی که دادین مشکلم حل شد ♥

**Comment by Rooohi76** [comment]
> محتوای`geosite-whatsapp.srs` :

> محتوای `geoip-telegram.srs` :

عذرخواهی میکنم محتوای فایلها رو از چه طریقی میشه مشاهده کرد که بفهمیم هرکدوم شامل چه آدرسیه؟

کلا جایی میشه توضیح کوتاهی درمورد کاربرد هر فایل و همپوشانی اون با فایلای دیگه پیدا کرد؟
دنبال یه چیز مختصری هستم در حد توضیحاتی که همین ریپو درمورد یه سری فایلها داده

با تشکر
