### ISSUE TITLE
چطوری میشه این رو جایگزین دیتابیس دیفالت nekoray کرد؟

### ISSUE THREAD

**Issue by Weirdo1312** [Chocolate4U/Iran-sing-box-rules#4]

**Comment by Chocolate4U** [comment]
اگر از هسته sing-box استفاده می کنید، فایل های `geoip.db` و `geosite.db` رو دانلود کنید و در پوشه nekoray بریزید و پیغام جایگزینی رو هم تایید کنید. اگر از هسته xray استفاده می کنید باید فایل های `geoip.dat` و `geosite.dat` رو از ریپوی Iran-v2ray-rules دانلود کنید و در پوشه nekoray بریزید.
