### ISSUE TITLE
GeoIP-Lite and IR CDNs

### ISSUE THREAD

**Issue by alidxdydz** [Chocolate4U/Iran-sing-box-rules#5]
سلام دوست عزیز.
خسته نباشی.
برام سوال ایجاد شده بود که با توجه به اینکه تو دیتابیس GeoIP هر کدوم از CDN های ایرانی جدا شدن، تو دیتابیس GeoIP-Lite دسته ir شامل IP های مربوط به CDN های ایرانی میشه یا نه؟

**Comment by msshn** [comment]
سلام.
نه، GeoIP-Lite فقط شامل IP های ایران موجود در دو دیتابیس MaxMind و IP2Location میشه.
البته بخش زیادی از IP های CDN های ایرانی توی همین دیتابیس ها موجوده،

**Comment by Chocolate4U** [comment]
سلام.
نه، GeoIP-Lite فقط شامل IP های ایران موجود در دیتابیس های MaxMind و IP2Location میشه.
البته بخش زیادی از IP های CDN های ایرانی توی همین دیتابیس ها موجوده.
