### ISSUE TITLE
Geoip Af for bypass

### ISSUE THREAD

**Issue by Graveyard9988** [Chocolate4U/Iran-sing-box-rules#7]
با درود
از انجایی که بسیاری از سایت های خبری خارجی در افعانستان مسدود شده است‌، به هنگام استفاده از فیلترشکن آیپی خارجی کاربر برای سایت های دولتی قابل رصد و مشاهده است‌ ، بنابراین در صورت امکان geoip:af را به فایل خود اضافه کنید تا آیپی های داخلی افغانستان در صورت انتخاب کاربر بای پس شود

لازم به ذکر است که مخرن فایل های db شما در هیدیفای نکست قرار گرفته و اگر geoip:af را به فایل geoip.db و geoip.dat اضافه کنید، کمک شایان و بزرگی به مردمان افغانستان در جهت حفظ حریم خصوصی و امنیت آنها خواهید کرد
تعداد آیپی های داخلی این کشور نسبت به ایران کمتر است و طبیعتا حجم زیادی را اشغال نخواهد کرد.

با سپاس از توجه و زحمات شما

**Comment by Graveyard9988** [comment]
لطفا بررسی کنید
با سپاس

**Comment by Chocolate4U** [comment]
سلام
اضافه شد و در آپدیت بعدی اعمال میشه.

**Comment by Chocolate4U** [comment]
> ظاهرا در اپدیت dat اعمال شده ولی در اپدیت db هنوز اعمال نشده

تغییرات جدیدی داده شده و فایل geoip جامع تر شده، لطفا دوباره تست کنید ببینید مشکل برطرف شده یا خیر.

**Comment by Graveyard9988** [comment]
سپاس فراوان
در چنج لاگ ریپو، فایل db اثری از geoip:af ندیدم
ایا در فایل db اعمال شده؟ 
چون می خواهم در کلاینت و سرور همزمان اعمال کنم می پرسم

**Comment by Graveyard9988** [comment]
اعمال شده
تشکر فراوان

لطفا مستندات را به روز کنید

**Comment by Graveyard9988** [comment]
سپاس بی کران
مشکلات بسیاری رفع شده به لطف و پیگیری و زحمات شما
