### ISSUE TITLE
تغییر در فرمت فایل های جئو از هسته جدید 1.8

### ISSUE THREAD

**Issue by Graveyard9988** [Chocolate4U/Iran-sing-box-rules#8]
درود
ظاهرا فرمت و ساختار فایل های geo سینگ باکس از هسته 1.8 تغییر کرده است. مثال:
https://github.com/ZloZloe39/new-sing-geo
 لطفا نسبت به ایجاد فایل های جدید (علاوه بر قبلی) بررسی و اقدام کنید

سپاس

**Comment by Chocolate4U** [comment]
سلام
فعلا منتظرم نسخه نهایی منتشر بشه چون این نسخه هنوز در مرحله Alpha هست و امکان به وجود اومدن تغییرات در نسخه نهایی وجود داره.

**Comment by Graveyard9988** [comment]
https://github.com/PaPerseller/chn-iplist/blob/master/sing-box_client_ruleset.json


بیشتر صفحات چینی در حال راه اندازی فایل های جئو با فرمت و قالب جدید هستن

**Comment by Chocolate4U** [comment]
اضافه شد. https://github.com/Chocolate4U/Iran-sing-box-rules/commit/3c8d677e8db0fd8f35883954364159eb183504cf

**Comment by Graveyard9988** [comment]
در صورت امکان با فرمت جدید، موارد زیر را ایجاد و اضافه کنید:
geoip-af
geoip تمام کشور ها
geosite تمام کشور ها

سپاس

**Comment by Graveyard9988** [comment]
ایا با فرمت جدید
Geoip-ir
Geosite-ir
برای شما در اخرین بتا سینگ باکس بای پس می شود؟

برای من کار نکرد با اینکه چند بار بررسی و تست کردم

**Comment by Graveyard9988** [comment]
سپاس بی کران

**Comment by Graveyard9988** [comment]
یک‌مشکل هستش
صفحات
Downloadly.ir 
به دامین downloadlynet.ir ریدایرکت می شود که مختص خارج از کشور است.

ممنون می شوم این مشکل را بررسی و برطرف کنید
