### ISSUE TITLE
蓝奏盘的下载会proxy 是我自己没设置对 还是IP库的问题？

### ISSUE THREAD

**Issue by EastJerry** [Chocolate4U/Iran-sing-box-rules#9]
蓝奏盘的下载会proxy 是我自己没设置对 还是IP库的问题？

**Comment by Chocolate4U** [comment]
Please use English.
The IP library is from MaxMind/IP2Location and is not 100% accurate, also you may want to use Loyalsoldier/soffchen repository as it may have better accuracy for China IPs.
